// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlkMMdGv2TkuGh317g8bE8w3ixtOrdQEo',
    appId: '1:32436198035:web:47086028a9aebf9d330b66',
    messagingSenderId: '32436198035',
    projectId: 'iot-24-b9060',
    authDomain: 'iot-24-b9060.firebaseapp.com',
    storageBucket: 'iot-24-b9060.appspot.com',
    measurementId: 'G-26QRCLEE3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgVvnHYUV3xuOpLUBN210iKnSybDBPt6U',
    appId: '1:32436198035:android:4cbb4d296e491f4a330b66',
    messagingSenderId: '32436198035',
    projectId: 'iot-24-b9060',
    storageBucket: 'iot-24-b9060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCua-ndP4aXboqqq79bab_OpDKD8Z2Opg',
    appId: '1:32436198035:ios:adca40fcd9232961330b66',
    messagingSenderId: '32436198035',
    projectId: 'iot-24-b9060',
    storageBucket: 'iot-24-b9060.appspot.com',
    iosBundleId: 'com.example.fissy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCua-ndP4aXboqqq79bab_OpDKD8Z2Opg',
    appId: '1:32436198035:ios:adca40fcd9232961330b66',
    messagingSenderId: '32436198035',
    projectId: 'iot-24-b9060',
    storageBucket: 'iot-24-b9060.appspot.com',
    iosBundleId: 'com.example.fissy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlkMMdGv2TkuGh317g8bE8w3ixtOrdQEo',
    appId: '1:32436198035:web:5ecee7481ea40e97330b66',
    messagingSenderId: '32436198035',
    projectId: 'iot-24-b9060',
    authDomain: 'iot-24-b9060.firebaseapp.com',
    storageBucket: 'iot-24-b9060.appspot.com',
    measurementId: 'G-5LWEDN1RYE',
  );
}
